[bell]
animation = "EaseOutExpo"
color = "#444267"
duration = 2

[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xf78c6c"
index = 16

[[colors.indexed_colors]]
color = "0xff5370"
index = 17

[[colors.indexed_colors]]
color = "0x444267"
index = 18

[[colors.indexed_colors]]
color = "0x32374d"
index = 19

[[colors.indexed_colors]]
color = "0x8796b0"
index = 20

[[colors.indexed_colors]]
color = "0x959dcb"
index = 21

[colors.bright]
black = "0x665c54"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xfbf1c7"
yellow = "0xfabd2f"

[colors.cursor]
cursor = "0xd5c4a1"
text = "0x1d2021"

[colors.normal]
black = "0x1d2021"
blue = "0x83a598"
cyan = "0x8ec07c"
green = "0xb8bb26"
magenta = "0xd3869b"
red = "0xfb4934"
white = "0xd5c4a1"
yellow = "0xfabd2f"

[colors.primary]
background = "0x1d2021"
foreground = "0xd5c4a1"

[font]
size = 14.0

[font.bold]
family = "Iosevka"
style = "Medium"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Iosevka"
style = "Light Italic"

[font.normal]
family = "Iosevka"
style = "Light"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "Return"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOH"
key = "Left"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[H"
key = "Left"
mode = "~AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001BOF"
key = "Right"
mode = "AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[F"
key = "Right"
mode = "~AppCursor"
mods = "Command"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001B\u007F"
key = "Back"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "PageUp"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "PageDown"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mods = "Shift"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mods = "Shift"

[mouse]
hide_when_typing = true

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>\t"

[shell]
args = ["--login"]
program = "/opt/homebrew/bin/fish"

[window]
decorations = "buttonless"
dynamic_title = true
opacity = 1.0
startup_mode = "Windowed"

[window.dimensions]
columns = 2
lines = 0

[window.padding]
x = 10
y = 15
